sudo: false
language: ruby

rvm:
  - 2.0.0
  - 2.1.2
  - 2.2.3
  - 2.3.1
  - 2.4.1

addons:
  code_climate:
    repo_token: 682975bb1f8c2c0c4b854034c70744758c50c832e28c563d8a7e7bdabf821e34

before_install: gem install bundler -v 1.15.3

cache:
  - bundler

script:
  - bundle exec rake

after_success:
  - bundle exec codeclimate-test-reporter
