sudo: false
language: ruby

rvm:
  - 2.6.5
  - 2.7.2

addons:
  code_climate:
    repo_token: 682975bb1f8c2c0c4b854034c70744758c50c832e28c563d8a7e7bdabf821e34

before_install: gem install bundler -v 2.1.4

cache:
  - bundler

script:
  - bundle exec rake

after_success:
  - bundle exec codeclimate-test-reporter
